### ISSUE TITLE
Can I help you have this in formly-js org

### ISSUE THREAD

**Issue by mohammedzamakhan** [matt-sanders/vue-formly#2]
formly-js is an organization where we have Angular 1, Angular 2 and React Formly versions. Do you want to help you have this in formly-js organization for vue2.0?

**Comment by matt-sanders** [comment]
hiya, that sounds interesting. I've actually already got plans for vue-formly support for vue2.0, it's not going to require much change to get it to work, I've just been trying to find the time to do it. But being part of formly-js sounds cool, what's involved with that?

**Comment by mohammedzamakhan** [comment]
I can add you to formly-js organization and create the vue-formly repo there.

**Comment by mohammedzamakhan** [comment]
https://github.com/formly-js/vue-formly

**Comment by matt-sanders** [comment]
Awesome, thanks Mohammed! I'm hoping to have some free time soon to finish off VF2.0 so I'll start porting everything over soon.
